### PR TITLE
added SSLyze capability to print (EC)DH groups informations

### PR DESCRIPTION
**Pull request by elvanderb**
stdout and xml supported.
For stdout: print group type and group size (ECDH-256 bits or DH-2048 bits for example).
For xml: gives some informations about the group (generator, group size, type, prime etc.).

To work, this patch needs the pull request I made for nassl to be accepted :)

### CODE REVIEW

**Comment by wsargent** [comment]
Excellent.  I'm still confused why ECDHE is 256 bits when a DHE key exchange can be 2048 bits :-/

EDIT: because one uses elliptic curves and the other doesn't, I know...

**Comment by elvanderb** [comment]
Elliptic curve cryptography is much more robust than GF(p) base one.

256 bit for discrete log on EC ~ 128 bit symetric (AES for example) ~ 3072 bit for discrete log on GF(p) ("classic" Diffie Hellman)  / factorisation (RSA).

**Comment by badroum** [comment]
hi,
where is the release for this commit.
thx.

**Comment by nabla-c0d3** [comment]
Hi,
I haven't had time to merge this yet.

**Comment by badroum** [comment]
Hi,
And when do you think to do?
Because this upgrade it very interesting for me.

**Comment by nabla-c0d3** [comment]
it's very interesting feature indeed, but I don't know yet when I will have time to merge this pull request.

**Comment by nabla-c0d3** [comment]
Just merged this, finally. Thanks again, awesome feature!

**Comment by elvanderb** [comment]
Thank you ;)

**Pull request closed without merging**
