### PR TITLE
Http strict transport security plugin

### PR DESCRIPTION
**Pull request by secworks**
This patch adds a plugin for testing support for HSTS.

### CODE REVIEW

**Comment by nabla-c0d3** [comment]
Thanks! Will look into it asap

**Comment by secworks** [comment]
Note that the patch does not use the ssl_ctx, ctSSL but instead use the SSL support available in Python std lib.

**Comment by jschlyter** [comment]
Any updates on this feature?

**Comment by nabla-c0d3** [comment]
I was hesitant because this is an HTTP only scan, but SSLyze supports other protocols (with starttls) so there might be problems. I'll merge it anyway because it seems like quite a few people want this feature in.

**Comment by secworks** [comment]
Aloha!

Alban Diquet wrote:

> I was hesitant because this is an HTTP only scan, but SSLyze supports
> other protocols (with starttls) so there might be problems. I'll merge
> it anyway because it seems like quite a few people want this feature in.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/iSECPartners/sslyze/pull/26#issuecomment-22653397.

Thanks!

**Pull request merged**
