### PR TITLE
Add OpenSSL cipher strength to output

### PR DESCRIPTION
**Pull request by bcyrill**
This patch will add an additional column showing the strength of the cipher as rated by OpenSSL. Requires the OpenSSL wrapper modifications in https://github.com/nabla-c0d3/nassl/pull/8

### CODE REVIEW

**Comment by nabla-c0d3** [comment]
Thanks for all the pull requests! Will look into this next week.

**Comment by nabla-c0d3** [comment]
Thanks for all the pull requests. This one requires too many changes and touches nassl too, for something that I don't think SSLyze needs. The three existing columns for checking cipher suites are already hard to read and display a lot of information. I also think the cipher strength is somewhat redundant with the key length that is already displayed for each cipher. For these reasons, I don't think I will merge this request but thanks for all your contributions!

**Comment by bcyrill** [comment]
Actually, having an easy to read indicator of the cipher strength, was one of the reasons why I have added the strength, as defined in OpenSSL, directly to the output. Especially for the ciphers with a 128 bit key, which are probably still the most commonly used ones, the existing output would not allow to quickly differentiate between MEDIUM and HIGH strength ciphers.

I tried to keep the changes to a minimum and modified nassl to only expose OpenSSL's algo_strength and do some prettifying before returning the value.

Would you consider adding OpenSSL's strength when I made the output optional and off by default? Yeah, I know that would mean that there's yet another command-line parameter.

**Comment by nabla-c0d3** [comment]
Yes I could definitely see that you tried to keep your changes to a minimum and I appreciate that. I still need to think about this and other options. Something as simple as a user manual that explains how to understand a scan result could be enough, perhaps.

**Comment by tomrittervg** [comment]
Sorry, development is not longer be conducted in this repository, please resubmit the pull request if interested at https://github.com/nabla-c0d3/sslyze

**Pull request closed without merging**
