### PR TITLE
export: added JSON support

### PR DESCRIPTION
**Pull request by rogerc**
JSON support as mentioned in issue #23.
- It uses the XML document as the source and converts it to JSON. It uses 'xmltodict' to convert the final version of the document to JSON.
- Added new option to settings to define filename for the JSON output.

### CODE REVIEW

**Comment by nabla-c0d3** [comment]
Thanks ! Will look into this when I have time.

**Comment by nabla-c0d3** [comment]
Just merged your pull request. Thanks!

**Comment by nabla-c0d3** [comment]
I had to revert your changes because I didn't realize that xmltodict was not a standard library. I want to keep the number of dependencies as low as possible so I will need to think about the right thing to do here.

**Comment by qrpike** [comment]
Any updates? This would be really nice to have. Thanks.

**Pull request merged**
