### PR TITLE
Multiple trust stores

### PR DESCRIPTION
**Pull request by secworks**
This patch updates PluginCertInfo to support use of multiple trust stores and EV validation using multiple CA roots.

Trust stores are expected to be available as files with multiple certs in PEM-format and the files when the plugin is loaded. For each Trust Store, sslyze creates a separate SSL_ctx and loads the Trust Store before verifying the trust chain and the result for each of the Trust Stores are reported separately.

The EV validation files are no longer a Python list that is included into the code, but instead JSON-files that contains OIDs, fingerprints and certinfo. Currently only OIDs are used by the EV-validation. Validation and result is reported separately for each file loaded.

This patch also adds a common verbosity flag to sslyze to allow different levels of verbosity/debug information to be presented to the user.

### CODE REVIEW

**Comment by jschlyter** [comment]
Any updates on this pull request? I believe we (@secheads and myself) are now ready for integration.
For CA root and EV sources, please see https://github.com/kirei/catt

**Comment by nabla-c0d3** [comment]
It's a really cool feature especially with the scripts you have. However, PluginCertinfo is bloated and huge already (now with OCSP stapling), so I would want this to be part of a separate plugin. Also, the two branches have diverged and merging this pull request will not work anymore. So if you guys could do the following (which shouldn't take too much time):
- Get the current PluginCertInfo (ie. clone the current master branch) and modify it with your code 
- Name it something else
- Open a pull request

Then I'll merge the request right away. 
Thanks! and let me know if you need some help.

**Comment by secworks** [comment]
Sure, I'll do that.

I considered making separate plugins for CRL, OCSP etc but decided against it. The reasons being that these checks sort of belonged/was related to the verification of the certificate. Another reason was to avoid duplicating a lot of code.

Specifically the X509CertificateHelper class would have to be duplicated as it is right now. But if we could refactor it to a common module it is more than fine by me. Why not call it CertificateHelper or CertificateParser or similar?

Anyway. I'll start moving CRL, OCSP to separate plugins.
Thanks for the feedback!

**Comment by secworks** [comment]
And of course also make a plugin for multiple trust stores.
Will you deprecate the old trust store, EV-checks in the old CertInfo?

**Comment by nabla-c0d3** [comment]
I don't know yet if I'll deprecate the old trust store. I might do it eventually, or let the two plugins coexist.

**Comment by secworks** [comment]
Ok. I'll create branches for the different plugins as well as refactoring of the certparser object and send pull requests when things seems to work as expected.

**Comment by secworks** [comment]
I have moved the X509CertificateHelper class and the dns_to_pat function to a new module utils/CertParser.py to allow us to share these functions in the new plugins. The new module is in commit 259c9feaaf966079f487d9e9a29eda8679432870

There is also an updated version of PluginCertInfo that use the new CertParser module. You might want to cherry pick from that one.:
a1faee6d606f5f21f229a220deaa72ae09814500

**Comment by nabla-c0d3** [comment]
PluginTrustTracker now has the same functionality.

**Pull request closed without merging**
