### PR TITLE
Plugin multiple trust stores

### PR DESCRIPTION
**Pull request by secworks**
Here is the separate plugin for multiple trust stores.
Note that this plugin assumes that utils/CertParser is available.

### CODE REVIEW

**Comment by nabla-c0d3** [comment]
Hi,
Thanks for the contribution. However, you are still using the old branch :(. Please clone the current master branch, otherwise the pull requests will not work. Remember that ctSSL is gone now so all this code will fail and I can't merge it (you can't do from utils.ctSSL import ctSSL_initialize anymore for example). 

For now, I'm going to write PluginMultipleTrustStores myself using your code, so I can show you how to do it on the current master branch. Thanks again for all the help

**Comment by nabla-c0d3** [comment]
Okay, have a look and let me know what you think:
https://github.com/iSECPartners/sslyze/commit/c24180e1c62aca8cc75bbebc20969402f1f4c4f0

**Comment by secworks** [comment]
The problem is that we are still on the old branch for the kirei/sslyze and need to finish the project development.

The patch looks good - but where the x509 parser go?

**Comment by nabla-c0d3** [comment]
It's now in nassl.X509Certificate.as_dict().

**Pull request closed without merging**
