### PR TITLE
Add checking for session ticket key rotation.

### PR DESCRIPTION
**Pull request by jsha**
This checks that hosts negotiating DH cipher suites do ticket key rotation correctly: https://www.imperialviolet.org/2013/06/27/botchingpfs.html.

### CODE REVIEW

**Comment by nabla-c0d3** [comment]
This is cool, thanks!
Have you seen a lot of servers that don't rotate their TLS ticket keys ? I'll do some testing and merge this code asap; I will make this check a separate command (otherwise it will slow down scans a lot).

**Comment by jsha** [comment]
I haven't seen a lot of servers making this mistake, but not many servers implement both forward secrecy and session tickets. I intended this mainly as a tool for administrators who want to check that their implementation is correct, and secondarily to provide a warning to administrators who may be running sslyze but not know to check for this interaction.

**Comment by nabla-c0d3** [comment]
Yeah that makes sense. I need to figure out a way to integrate this functionality because right now it just makes the tool sleep for X amount of time (such as 2 days on the servers I tested it against).

**Comment by jsha** [comment]
May it makes more sense to have --resum issue a warning when it sees DH + session tickets, and offer an alternate flag --ticket_key_rotate that does the sleeping?

Or --resum could issue the warning + output the assigned ticket's key_name in hex and instruct the user to re-run in X hours or days and verify that the key_name changes.

**Comment by tomrittervg** [comment]
Sorry, development is not longer be conducted in this repository, please resubmit the pull request if interested at https://github.com/nabla-c0d3/sslyze

**Pull request closed without merging**
